spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vollmed_api
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:murilo70}

server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET:123456}
